# 异常处理

## 标准异常

异常是程序在执行期间产生的问题。C++ 异常是指在程序运行时发生的特殊情况，比如尝试除以零的操作。
异常提供了一种转移程序控制权的方式。C++ 异常处理涉及到三个关键字：`try、catch、throw`。

```
try{
   // 保护代码
}catch( ExceptionName e1 ){
   // catch 块
}catch( ExceptionName e2 ){
   // catch 块
}catch( ExceptionName eN ){
   // catch 块
}
```


C++ 提供了一系列标准的异常，它们被定义在四个头文件中。

- exception头文件中定义了最通用的异常类exception，只报告异常的发生，不提供任何信息
- stdexcept头文件定义了几种常用的异常
- new头文件定义了bad_alloc异常类型
- type_info头文件定义了bad_cast异常

常见异常如下所示：

- `std::exception`	该异常是所有标准 C++ 异常的父类。
- `std::bad_alloc`	该异常可以通过 new 抛出。
- `std::bad_cast`	该异常可以通过 dynamic_cast 抛出。
- `std::bad_exception`	这在处理 C++ 程序中无法预期的异常时非常有用。
- `std::bad_typeid`	该异常可以通过 typeid 抛出。
- `std::logic_error`	理论上可以通过读取代码来检测到的异常。
- `std::domain_error`	当使用了一个无效的数学域时，会抛出该异常。
- `std::invalid_argument`	当使用了无效的参数时，会抛出该异常。
- `std::length_error`	当创建了太长的 std::string 时，会抛出该异常。
- `std::out_of_range`	该异常可以通过方法抛出，例如 `std::vector` 和 `std::bitset<>::operator[]()`。
- `std::runtime_error`	理论上不可以通过读取代码来检测到的异常。
- `std::overflow_error`	当发生数学上溢时，会抛出该异常。
- `std::range_error`	当尝试存储超出范围的值时，会抛出该异常。
- `std::underflow_error`	当发生数学下溢时，会抛出该异常。	

只能以默认初始化的方式初始化exception、bad_alloc、bad_cast异常，不能为它们提供任何初始化值，而其他异常在初始化时，需要提供string类型的异常信息。
